--
-- PostgreSQL database dump
--

\restrict eMko3UzOnaraum44pKBQoXtS24fNnt5LDhkfQrGfYkhXRzhUKGgqlv01ayF937X

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: tienda_carrito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_carrito (
    id bigint NOT NULL,
    creado timestamp with time zone NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.tienda_carrito OWNER TO postgres;

--
-- Name: tienda_carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.tienda_categoria OWNER TO postgres;

--
-- Name: tienda_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_cliente (
    id bigint NOT NULL,
    direccion character varying(255) NOT NULL,
    telefono character varying(20) NOT NULL,
    ciudad character varying(100) NOT NULL,
    departamento character varying(100) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.tienda_cliente OWNER TO postgres;

--
-- Name: tienda_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_cupondescuento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_cupondescuento (
    id bigint NOT NULL,
    codigo character varying(20) NOT NULL,
    descuento numeric(5,2) NOT NULL,
    valido_desde date NOT NULL,
    valido_hasta date NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.tienda_cupondescuento OWNER TO postgres;

--
-- Name: tienda_cupondescuento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_cupondescuento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_cupondescuento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_detallepedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_detallepedido (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    pedido_id bigint NOT NULL,
    producto_id bigint
);


ALTER TABLE public.tienda_detallepedido OWNER TO postgres;

--
-- Name: tienda_detallepedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_detallepedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_detallepedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_detalleproducto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_detalleproducto (
    id bigint NOT NULL,
    detalles text NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.tienda_detalleproducto OWNER TO postgres;

--
-- Name: tienda_detalleproducto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_detalleproducto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_detalleproducto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_historialestadopedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_historialestadopedido (
    id bigint NOT NULL,
    estado character varying(50) NOT NULL,
    fecha_cambio timestamp with time zone NOT NULL,
    pedido_id bigint NOT NULL
);


ALTER TABLE public.tienda_historialestadopedido OWNER TO postgres;

--
-- Name: tienda_historialestadopedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_historialestadopedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_historialestadopedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_inventario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_inventario (
    id bigint NOT NULL,
    cantidad_actual integer NOT NULL,
    actualizado timestamp with time zone NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.tienda_inventario OWNER TO postgres;

--
-- Name: tienda_inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_itemcarrito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_itemcarrito (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    carrito_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.tienda_itemcarrito OWNER TO postgres;

--
-- Name: tienda_itemcarrito_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_itemcarrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_itemcarrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_metodopago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_metodopago (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.tienda_metodopago OWNER TO postgres;

--
-- Name: tienda_metodopago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_metodopago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_metodopago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_pago (
    id bigint NOT NULL,
    fecha_pago timestamp with time zone NOT NULL,
    referencia character varying(100) NOT NULL,
    estado character varying(50) NOT NULL,
    metodo_id bigint,
    pedido_id bigint NOT NULL
);


ALTER TABLE public.tienda_pago OWNER TO postgres;

--
-- Name: tienda_pago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_pedido (
    id bigint NOT NULL,
    fecha_pedido timestamp with time zone NOT NULL,
    total numeric(10,2) NOT NULL,
    direccion_envio character varying(255) NOT NULL,
    estado_actual character varying(50) NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.tienda_pedido OWNER TO postgres;

--
-- Name: tienda_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_producto (
    id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    imagen character varying(100),
    fecha_creacion timestamp with time zone NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE public.tienda_producto OWNER TO postgres;

--
-- Name: tienda_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_profile (
    id bigint NOT NULL,
    whatsapp character varying(20),
    puntos integer NOT NULL,
    direccion text,
    user_id integer NOT NULL
);


ALTER TABLE public.tienda_profile OWNER TO postgres;

--
-- Name: tienda_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_resenaproducto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_resenaproducto (
    id bigint NOT NULL,
    puntuacion integer NOT NULL,
    comentario text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    cliente_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.tienda_resenaproducto OWNER TO postgres;

--
-- Name: tienda_resenaproducto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_resenaproducto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_resenaproducto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tienda_userotp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tienda_userotp (
    id bigint NOT NULL,
    otp_code character varying(4),
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.tienda_userotp OWNER TO postgres;

--
-- Name: tienda_userotp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tienda_userotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tienda_userotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add tienda categoria	7	add_tiendacategoria
26	Can change tienda categoria	7	change_tiendacategoria
27	Can delete tienda categoria	7	delete_tiendacategoria
28	Can view tienda categoria	7	view_tiendacategoria
29	Can add tienda cupondescuento	8	add_tiendacupondescuento
30	Can change tienda cupondescuento	8	change_tiendacupondescuento
31	Can delete tienda cupondescuento	8	delete_tiendacupondescuento
32	Can view tienda cupondescuento	8	view_tiendacupondescuento
33	Can add tienda metodopago	9	add_tiendametodopago
34	Can change tienda metodopago	9	change_tiendametodopago
35	Can delete tienda metodopago	9	delete_tiendametodopago
36	Can view tienda metodopago	9	view_tiendametodopago
37	Can add tienda cliente	10	add_tiendacliente
38	Can change tienda cliente	10	change_tiendacliente
39	Can delete tienda cliente	10	delete_tiendacliente
40	Can view tienda cliente	10	view_tiendacliente
41	Can add tienda carrito	11	add_tiendacarrito
42	Can change tienda carrito	11	change_tiendacarrito
43	Can delete tienda carrito	11	delete_tiendacarrito
44	Can view tienda carrito	11	view_tiendacarrito
45	Can add tienda pedido	12	add_tiendapedido
46	Can change tienda pedido	12	change_tiendapedido
47	Can delete tienda pedido	12	delete_tiendapedido
48	Can view tienda pedido	12	view_tiendapedido
49	Can add tienda pago	13	add_tiendapago
50	Can change tienda pago	13	change_tiendapago
51	Can delete tienda pago	13	delete_tiendapago
52	Can view tienda pago	13	view_tiendapago
53	Can add tienda historialestadopedido	14	add_tiendahistorialestadopedido
54	Can change tienda historialestadopedido	14	change_tiendahistorialestadopedido
55	Can delete tienda historialestadopedido	14	delete_tiendahistorialestadopedido
56	Can view tienda historialestadopedido	14	view_tiendahistorialestadopedido
57	Can add tienda producto	15	add_tiendaproducto
58	Can change tienda producto	15	change_tiendaproducto
59	Can delete tienda producto	15	delete_tiendaproducto
60	Can view tienda producto	15	view_tiendaproducto
61	Can add tienda itemcarrito	16	add_tiendaitemcarrito
62	Can change tienda itemcarrito	16	change_tiendaitemcarrito
63	Can delete tienda itemcarrito	16	delete_tiendaitemcarrito
64	Can view tienda itemcarrito	16	view_tiendaitemcarrito
65	Can add tienda inventario	17	add_tiendainventario
66	Can change tienda inventario	17	change_tiendainventario
67	Can delete tienda inventario	17	delete_tiendainventario
68	Can view tienda inventario	17	view_tiendainventario
69	Can add tienda detalleproducto	18	add_tiendadetalleproducto
70	Can change tienda detalleproducto	18	change_tiendadetalleproducto
71	Can delete tienda detalleproducto	18	delete_tiendadetalleproducto
72	Can view tienda detalleproducto	18	view_tiendadetalleproducto
73	Can add tienda detallepedido	19	add_tiendadetallepedido
74	Can change tienda detallepedido	19	change_tiendadetallepedido
75	Can delete tienda detallepedido	19	delete_tiendadetallepedido
76	Can view tienda detallepedido	19	view_tiendadetallepedido
77	Can add tienda resenaproducto	20	add_tiendaresenaproducto
78	Can change tienda resenaproducto	20	change_tiendaresenaproducto
79	Can delete tienda resenaproducto	20	delete_tiendaresenaproducto
80	Can view tienda resenaproducto	20	view_tiendaresenaproducto
81	Can add profile	21	add_profile
82	Can change profile	21	change_profile
83	Can delete profile	21	delete_profile
84	Can view profile	21	view_profile
85	Can add user otp	22	add_userotp
86	Can change user otp	22	change_userotp
87	Can delete user otp	22	delete_userotp
88	Can view user otp	22	view_userotp
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
4	pbkdf2_sha256$1000000$AXsN0rXO60y7vb2vC7NCE5$997gDL+GjR7wqKJxYutuveiHyZzNu95XW6Ai6DEaBEI=	2026-01-20 12:25:08-05	t	mildev	Carlos	Ruiz	mildev@gmail.com	t	t	2026-01-20 12:24:00-05
5	!gM5VOgxXm9zzMSX2rU3PhGIXhByQh4X3shrTs06A	\N	f	carlos288913@gmail.com			carlos288913@gmail.com	f	t	2026-02-09 14:21:49.096992-05
6	!5cTmx3mkK0KxzwHMlwE3GlGY5LdR76wWcDLb27JN	\N	f	expomarket8@gmail.com			expomarket8@gmail.com	f	t	2026-02-09 15:25:45.790055-05
7	pbkdf2_sha256$1000000$JWrAZ54Gqrf8CDhrp1Stuk$x6is1S/Q08u7YrEKaf4x9Poy4FHkYcsLnBSc9YjkBEQ=	2026-02-20 12:46:49.114721-05	t	careuiz			carlos28913@gmail.com	t	t	2026-02-20 12:46:13.560991-05
8	!QDD3WtohAnZwuNUzIZAjd9b8BmGxgnn5q55c4jNH	\N	f	PRUEBA1@GMAIL.COM			PRUEBA1@gmail.com	f	t	2026-02-20 20:44:08.59502-05
9	!9pgbrU24rmmnvWCaMnzuCybqfdjdgB0DC0ZQbNBX	\N	f	correonoexitente@gmail.com			correonoexitente@gmail.com	f	t	2026-02-20 21:12:54.515964-05
10	pbkdf2_sha256$1200000$GdjEKya18keHTE1a18RlhC$uWERfHXjrTI0huI+wCGRqAAl0HO6o85c+vUbIwe28yw=	2026-03-05 14:52:38.029725-05	t	admins			carlos@gmail.com	t	t	2026-03-05 14:51:08.242937-05
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
14	2026-01-20 12:26:47.38434-05	4	mildev	2	[{"changed": {"fields": ["First name", "Last name"]}}]	4	4
15	2026-02-20 19:53:47.221651-05	4	carlos288913@gmail.com	2	[]	10	7
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	tienda	tiendacategoria
8	tienda	tiendacupondescuento
9	tienda	tiendametodopago
10	tienda	tiendacliente
11	tienda	tiendacarrito
12	tienda	tiendapedido
13	tienda	tiendapago
14	tienda	tiendahistorialestadopedido
15	tienda	tiendaproducto
16	tienda	tiendaitemcarrito
17	tienda	tiendainventario
18	tienda	tiendadetalleproducto
19	tienda	tiendadetallepedido
20	tienda	tiendaresenaproducto
21	tienda	profile
22	tienda	userotp
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-28 12:40:34.334449-05
2	auth	0001_initial	2025-11-28 12:40:34.425809-05
3	admin	0001_initial	2025-11-28 12:40:34.4534-05
4	admin	0002_logentry_remove_auto_add	2025-11-28 12:40:34.462232-05
5	admin	0003_logentry_add_action_flag_choices	2025-11-28 12:40:34.472351-05
6	contenttypes	0002_remove_content_type_name	2025-11-28 12:40:34.489955-05
7	auth	0002_alter_permission_name_max_length	2025-11-28 12:40:34.500013-05
8	auth	0003_alter_user_email_max_length	2025-11-28 12:40:34.508746-05
9	auth	0004_alter_user_username_opts	2025-11-28 12:40:34.517231-05
10	auth	0005_alter_user_last_login_null	2025-11-28 12:40:34.526128-05
11	auth	0006_require_contenttypes_0002	2025-11-28 12:40:34.527315-05
12	auth	0007_alter_validators_add_error_messages	2025-11-28 12:40:34.535446-05
13	auth	0008_alter_user_username_max_length	2025-11-28 12:40:34.551866-05
14	auth	0009_alter_user_last_name_max_length	2025-11-28 12:40:34.561209-05
15	auth	0010_alter_group_name_max_length	2025-11-28 12:40:34.571982-05
16	auth	0011_update_proxy_permissions	2025-11-28 12:40:34.582841-05
17	auth	0012_alter_user_first_name_max_length	2025-11-28 12:40:34.592237-05
18	sessions	0001_initial	2025-11-28 12:40:34.603037-05
19	tienda	0001_initial	2025-11-28 12:40:34.823137-05
20	tienda	0002_alter_tiendacarrito_creado_alter_tiendacarrito_id_and_more	2025-12-04 16:29:07.755177-05
21	tienda	0003_profile_userotp	2026-02-09 08:04:27.218277-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
t7yy753b6wkvodcegfwgwmdz8yix2uhr	.eJxVjEEOwiAQRe_C2hCGqQN16d4zEGBAqgaS0q6MdzckXej2v_f-Wzi_b8XtPa1uYXERWpx-t-DjM9UB-OHrvcnY6rYuQQ5FHrTLW-P0uh7u30HxvYx6CueUCYmYwZgM7IHQUkYF2TLOPCGRMlpZpXNEYkxqZmvA20QA4vMF1vw3Gw:1vRwve:wNz3xLW-tLMw68Rdro-_E-j3YEW2zauzcntjpsocto4	2025-12-20 13:22:46.204431-05
fuzhueslol3dx3gbb95wwsn0d2iwmsgt	.eJxVjMsOwiAQAP9lz4YA5dmjd7-h2S6LVA0kpT0Z_9006UGvM5N5w4T7Vqa98zotCUYY4PLLZqQn10OkB9Z7E9Tqti6zOBJx2i5uLfHrerZ_g4K9wAiBiWNOIZI15IK0OSImFZCicibKbGarnFfaMwf2xtkh60FritpL7Rk-X-4QN2Q:1vht5l:-JaB5Gh73kdy9IuIxThIUQ0XKRFachoPkx47NUWoMnk	2026-02-02 12:31:05.289825-05
gwnpkjfadlisoalk5lr3nqv14tyke77v	.eJxVjLsOgzAMAP_FcxUBeWHG7v0G5MR2Q1uBRGCq-u8VEkO73p3uDSPtWxn3Kus4MQzg4PLLEuWnzIfgB833xeRl3tYpmSMxp63mtrC8rmf7NyhUCwzQZa-J2UalxIFaLxEx2F69qrJIxBZdFiUXmtaqON8poot9ox5t4-DzBRYNOF8:1viFTY:ykJFKO8EgWqMi1hvH0Ih9ztp933_GJy0RVLTXuE46TY	2026-02-03 12:25:08.222057-05
y554yonvkdjxe9w8ybsthas1ib6jw0f6	.eJxVjMsOwiAQRf-FtSGAPDou3fsNzQAzUjWQlHZl_HdD0oVu7znnvsWM-1bmvdM6L1lcRBCn3y1ielIdID-w3ptMrW7rEuVQ5EG7vLVMr-vh_h0U7GXUntnHBNoQTlbrAOiSNsZ5DhZSAGJkinj2mQFtYDVpcKAgZcXaO_H5AviMOCQ:1vtUaX:r-I2etOY17VHURFFbtg7coVhtNwjvonejptWiC1yjWo	2026-03-06 12:46:49.119006-05
06s91apjsfpwj631hcd7e161p6qfn1lk	.eJxVjDEOgzAMAP_iuYpwCCRh7N43IDt2GtoKJAJT1b9XSAztene6N4y0b2Xcq67jJDAANnD5hUzpqfNh5EHzfTFpmbd1YnMk5rTV3BbR1_Vs_waFaoEBrA0qNpP00WLCwOrbDlkxxMa3jrXP6H3rKVB2joWIrFcnIWrXESJ8vgeAODE:1vyEkQ:hTkcHzQX4bqUQU1FOYd4A6BfinEU4A-iZKvYDFGknKg	2026-03-19 14:52:38.045247-05
\.


--
-- Data for Name: tienda_carrito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_carrito (id, creado, cliente_id) FROM stdin;
\.


--
-- Data for Name: tienda_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_categoria (id, nombre, descripcion) FROM stdin;
1	Moluscos	Calamar peruano
2	Filetes	Filetes de salmón
\.


--
-- Data for Name: tienda_cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_cliente (id, direccion, telefono, ciudad, departamento, user_id) FROM stdin;
3	calle 8 eucaristico	3054316243	cali	Quindío	6
4	carrera 98 4-75	3054615797	cali	valle	5
5	calle 19 31a -11	3112345678	Medellin	Antioquia	9
\.


--
-- Data for Name: tienda_cupondescuento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_cupondescuento (id, codigo, descuento, valido_desde, valido_hasta, activo) FROM stdin;
\.


--
-- Data for Name: tienda_detallepedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_detallepedido (id, cantidad, precio_unitario, pedido_id, producto_id) FROM stdin;
\.


--
-- Data for Name: tienda_detalleproducto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_detalleproducto (id, detalles, producto_id) FROM stdin;
\.


--
-- Data for Name: tienda_historialestadopedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_historialestadopedido (id, estado, fecha_cambio, pedido_id) FROM stdin;
\.


--
-- Data for Name: tienda_inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_inventario (id, cantidad_actual, actualizado, producto_id) FROM stdin;
\.


--
-- Data for Name: tienda_itemcarrito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_itemcarrito (id, cantidad, carrito_id, producto_id) FROM stdin;
\.


--
-- Data for Name: tienda_metodopago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_metodopago (id, nombre) FROM stdin;
\.


--
-- Data for Name: tienda_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_pago (id, fecha_pago, referencia, estado, metodo_id, pedido_id) FROM stdin;
\.


--
-- Data for Name: tienda_pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_pedido (id, fecha_pedido, total, direccion_envio, estado_actual, cliente_id) FROM stdin;
\.


--
-- Data for Name: tienda_producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_producto (id, nombre, descripcion, precio, stock, imagen, fecha_creacion, categoria_id) FROM stdin;
1	Almejas	Blancas	38.50	3	\N	2026-01-19 13:01:21.268089-05	1
2	Langostino	Precocido  y crudos	98.00	3	\N	2026-01-19 13:02:56.395677-05	1
3	Filete de tilapia	Filete de tilapia fresco y delicioso	45.00	5	\N	2026-03-05 14:58:17.712954-05	1
\.


--
-- Data for Name: tienda_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_profile (id, whatsapp, puntos, direccion, user_id) FROM stdin;
1	573054316306	0	\N	5
2	573174262521	0	\N	6
3	\N	0	\N	7
4	3154262521	0	\N	8
5	32614985153	0	\N	9
6	\N	0	\N	10
\.


--
-- Data for Name: tienda_resenaproducto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_resenaproducto (id, puntuacion, comentario, fecha, cliente_id, producto_id) FROM stdin;
\.


--
-- Data for Name: tienda_userotp; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tienda_userotp (id, otp_code, created_at, user_id) FROM stdin;
2	7909	2026-02-09 15:25:49.345848-05	6
1	6685	2026-02-09 14:22:12.09523-05	5
3	4474	2026-02-20 19:58:55.144179-05	7
4	4841	2026-02-20 20:54:08.634148-05	8
5	4899	2026-02-20 21:13:01.454222-05	9
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 88, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 10, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 15, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 22, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- Name: tienda_carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_carrito_id_seq', 1, false);


--
-- Name: tienda_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_categoria_id_seq', 2, true);


--
-- Name: tienda_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_cliente_id_seq', 5, true);


--
-- Name: tienda_cupondescuento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_cupondescuento_id_seq', 1, false);


--
-- Name: tienda_detallepedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_detallepedido_id_seq', 1, false);


--
-- Name: tienda_detalleproducto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_detalleproducto_id_seq', 1, false);


--
-- Name: tienda_historialestadopedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_historialestadopedido_id_seq', 1, false);


--
-- Name: tienda_inventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_inventario_id_seq', 1, false);


--
-- Name: tienda_itemcarrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_itemcarrito_id_seq', 1, false);


--
-- Name: tienda_metodopago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_metodopago_id_seq', 1, false);


--
-- Name: tienda_pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_pago_id_seq', 1, false);


--
-- Name: tienda_pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_pedido_id_seq', 1, false);


--
-- Name: tienda_producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_producto_id_seq', 3, true);


--
-- Name: tienda_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_profile_id_seq', 6, true);


--
-- Name: tienda_resenaproducto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_resenaproducto_id_seq', 1, false);


--
-- Name: tienda_userotp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tienda_userotp_id_seq', 5, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: tienda_carrito tienda_carrito_cliente_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_carrito
    ADD CONSTRAINT tienda_carrito_cliente_id_key UNIQUE (cliente_id);


--
-- Name: tienda_carrito tienda_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_carrito
    ADD CONSTRAINT tienda_carrito_pkey PRIMARY KEY (id);


--
-- Name: tienda_categoria tienda_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_categoria
    ADD CONSTRAINT tienda_categoria_pkey PRIMARY KEY (id);


--
-- Name: tienda_cliente tienda_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_cliente
    ADD CONSTRAINT tienda_cliente_pkey PRIMARY KEY (id);


--
-- Name: tienda_cliente tienda_cliente_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_cliente
    ADD CONSTRAINT tienda_cliente_user_id_key UNIQUE (user_id);


--
-- Name: tienda_cupondescuento tienda_cupondescuento_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_cupondescuento
    ADD CONSTRAINT tienda_cupondescuento_codigo_key UNIQUE (codigo);


--
-- Name: tienda_cupondescuento tienda_cupondescuento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_cupondescuento
    ADD CONSTRAINT tienda_cupondescuento_pkey PRIMARY KEY (id);


--
-- Name: tienda_detallepedido tienda_detallepedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_detallepedido
    ADD CONSTRAINT tienda_detallepedido_pkey PRIMARY KEY (id);


--
-- Name: tienda_detalleproducto tienda_detalleproducto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_detalleproducto
    ADD CONSTRAINT tienda_detalleproducto_pkey PRIMARY KEY (id);


--
-- Name: tienda_detalleproducto tienda_detalleproducto_producto_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_detalleproducto
    ADD CONSTRAINT tienda_detalleproducto_producto_id_key UNIQUE (producto_id);


--
-- Name: tienda_historialestadopedido tienda_historialestadopedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_historialestadopedido
    ADD CONSTRAINT tienda_historialestadopedido_pkey PRIMARY KEY (id);


--
-- Name: tienda_inventario tienda_inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_inventario
    ADD CONSTRAINT tienda_inventario_pkey PRIMARY KEY (id);


--
-- Name: tienda_inventario tienda_inventario_producto_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_inventario
    ADD CONSTRAINT tienda_inventario_producto_id_key UNIQUE (producto_id);


--
-- Name: tienda_itemcarrito tienda_itemcarrito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_itemcarrito
    ADD CONSTRAINT tienda_itemcarrito_pkey PRIMARY KEY (id);


--
-- Name: tienda_metodopago tienda_metodopago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_metodopago
    ADD CONSTRAINT tienda_metodopago_pkey PRIMARY KEY (id);


--
-- Name: tienda_pago tienda_pago_pedido_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_pago
    ADD CONSTRAINT tienda_pago_pedido_id_key UNIQUE (pedido_id);


--
-- Name: tienda_pago tienda_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_pago
    ADD CONSTRAINT tienda_pago_pkey PRIMARY KEY (id);


--
-- Name: tienda_pedido tienda_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_pedido
    ADD CONSTRAINT tienda_pedido_pkey PRIMARY KEY (id);


--
-- Name: tienda_producto tienda_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_producto
    ADD CONSTRAINT tienda_producto_pkey PRIMARY KEY (id);


--
-- Name: tienda_profile tienda_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_profile
    ADD CONSTRAINT tienda_profile_pkey PRIMARY KEY (id);


--
-- Name: tienda_profile tienda_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_profile
    ADD CONSTRAINT tienda_profile_user_id_key UNIQUE (user_id);


--
-- Name: tienda_resenaproducto tienda_resenaproducto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_resenaproducto
    ADD CONSTRAINT tienda_resenaproducto_pkey PRIMARY KEY (id);


--
-- Name: tienda_userotp tienda_userotp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_userotp
    ADD CONSTRAINT tienda_userotp_pkey PRIMARY KEY (id);


--
-- Name: tienda_userotp tienda_userotp_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_userotp
    ADD CONSTRAINT tienda_userotp_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: tienda_cupondescuento_codigo_d0cc57f0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_cupondescuento_codigo_d0cc57f0_like ON public.tienda_cupondescuento USING btree (codigo varchar_pattern_ops);


--
-- Name: tienda_detallepedido_pedido_id_b3eb1187; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_detallepedido_pedido_id_b3eb1187 ON public.tienda_detallepedido USING btree (pedido_id);


--
-- Name: tienda_detallepedido_producto_id_1e766595; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_detallepedido_producto_id_1e766595 ON public.tienda_detallepedido USING btree (producto_id);


--
-- Name: tienda_historialestadopedido_pedido_id_557de9ea; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_historialestadopedido_pedido_id_557de9ea ON public.tienda_historialestadopedido USING btree (pedido_id);


--
-- Name: tienda_itemcarrito_carrito_id_f9ecbcdf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_itemcarrito_carrito_id_f9ecbcdf ON public.tienda_itemcarrito USING btree (carrito_id);


--
-- Name: tienda_itemcarrito_producto_id_607209aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_itemcarrito_producto_id_607209aa ON public.tienda_itemcarrito USING btree (producto_id);


--
-- Name: tienda_pago_metodo_id_ad1db38e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_pago_metodo_id_ad1db38e ON public.tienda_pago USING btree (metodo_id);


--
-- Name: tienda_pedido_cliente_id_e7f08ad0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_pedido_cliente_id_e7f08ad0 ON public.tienda_pedido USING btree (cliente_id);


--
-- Name: tienda_producto_categoria_id_6dc179b4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_producto_categoria_id_6dc179b4 ON public.tienda_producto USING btree (categoria_id);


--
-- Name: tienda_resenaproducto_cliente_id_a85259fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_resenaproducto_cliente_id_a85259fa ON public.tienda_resenaproducto USING btree (cliente_id);


--
-- Name: tienda_resenaproducto_producto_id_a92e3f11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tienda_resenaproducto_producto_id_a92e3f11 ON public.tienda_resenaproducto USING btree (producto_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_carrito tienda_carrito_cliente_id_ae212afb_fk_tienda_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_carrito
    ADD CONSTRAINT tienda_carrito_cliente_id_ae212afb_fk_tienda_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.tienda_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_cliente tienda_cliente_user_id_c12eac37_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_cliente
    ADD CONSTRAINT tienda_cliente_user_id_c12eac37_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_detallepedido tienda_detallepedido_pedido_id_b3eb1187_fk_tienda_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_detallepedido
    ADD CONSTRAINT tienda_detallepedido_pedido_id_b3eb1187_fk_tienda_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.tienda_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_detallepedido tienda_detallepedido_producto_id_1e766595_fk_tienda_producto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_detallepedido
    ADD CONSTRAINT tienda_detallepedido_producto_id_1e766595_fk_tienda_producto_id FOREIGN KEY (producto_id) REFERENCES public.tienda_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_detalleproducto tienda_detalleproduc_producto_id_9a695311_fk_tienda_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_detalleproducto
    ADD CONSTRAINT tienda_detalleproduc_producto_id_9a695311_fk_tienda_pr FOREIGN KEY (producto_id) REFERENCES public.tienda_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_historialestadopedido tienda_historialesta_pedido_id_557de9ea_fk_tienda_pe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_historialestadopedido
    ADD CONSTRAINT tienda_historialesta_pedido_id_557de9ea_fk_tienda_pe FOREIGN KEY (pedido_id) REFERENCES public.tienda_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_inventario tienda_inventario_producto_id_19a44b20_fk_tienda_producto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_inventario
    ADD CONSTRAINT tienda_inventario_producto_id_19a44b20_fk_tienda_producto_id FOREIGN KEY (producto_id) REFERENCES public.tienda_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_itemcarrito tienda_itemcarrito_carrito_id_f9ecbcdf_fk_tienda_carrito_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_itemcarrito
    ADD CONSTRAINT tienda_itemcarrito_carrito_id_f9ecbcdf_fk_tienda_carrito_id FOREIGN KEY (carrito_id) REFERENCES public.tienda_carrito(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_itemcarrito tienda_itemcarrito_producto_id_607209aa_fk_tienda_producto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_itemcarrito
    ADD CONSTRAINT tienda_itemcarrito_producto_id_607209aa_fk_tienda_producto_id FOREIGN KEY (producto_id) REFERENCES public.tienda_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_pago tienda_pago_metodo_id_ad1db38e_fk_tienda_metodopago_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_pago
    ADD CONSTRAINT tienda_pago_metodo_id_ad1db38e_fk_tienda_metodopago_id FOREIGN KEY (metodo_id) REFERENCES public.tienda_metodopago(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_pago tienda_pago_pedido_id_85725975_fk_tienda_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_pago
    ADD CONSTRAINT tienda_pago_pedido_id_85725975_fk_tienda_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.tienda_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_pedido tienda_pedido_cliente_id_e7f08ad0_fk_tienda_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_pedido
    ADD CONSTRAINT tienda_pedido_cliente_id_e7f08ad0_fk_tienda_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.tienda_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_producto tienda_producto_categoria_id_6dc179b4_fk_tienda_categoria_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_producto
    ADD CONSTRAINT tienda_producto_categoria_id_6dc179b4_fk_tienda_categoria_id FOREIGN KEY (categoria_id) REFERENCES public.tienda_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_profile tienda_profile_user_id_619fd58b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_profile
    ADD CONSTRAINT tienda_profile_user_id_619fd58b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_resenaproducto tienda_resenaproduct_producto_id_a92e3f11_fk_tienda_pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_resenaproducto
    ADD CONSTRAINT tienda_resenaproduct_producto_id_a92e3f11_fk_tienda_pr FOREIGN KEY (producto_id) REFERENCES public.tienda_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_resenaproducto tienda_resenaproducto_cliente_id_a85259fa_fk_tienda_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_resenaproducto
    ADD CONSTRAINT tienda_resenaproducto_cliente_id_a85259fa_fk_tienda_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.tienda_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tienda_userotp tienda_userotp_user_id_40b6eb3a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tienda_userotp
    ADD CONSTRAINT tienda_userotp_user_id_40b6eb3a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict eMko3UzOnaraum44pKBQoXtS24fNnt5LDhkfQrGfYkhXRzhUKGgqlv01ayF937X

