# Generated by Django 5.2.8 on 2026-03-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_profile_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tiendacategoria'),
        ),
    ]
