# Generated by Django 5.2.8 on 2026-03-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_tiendaproducto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.tiendacategoria'),
        ),
    ]
