# Generated by Django 6.0.2 on 2026-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_tiendaproducto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendacategoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
