# Generated by Django 6.0.2 on 2026-03-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_tiendaproducto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tiendacategoria'),
        ),
    ]
