# Generated by Django 6.0.2 on 2026-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_tiendacategoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
