# Generated by Django 6.0.2 on 2026-04-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_tiendaproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
