# Generated by Django 6.0.2 on 2026-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_tiendaproducto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendaproducto',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
