# Generated by Django 6.0.2 on 2026-04-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_tiendaproducto_categoria'),
        ('tienda', '0009_tiendaproducto_es_destacado'),
    ]

    operations = [
    ]
