# Generated by Django 6.0.2 on 2026-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_merge_20260411_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendaproducto',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='¿Está en oferta?'),
        ),
        migrations.AddField(
            model_name='tiendaproducto',
            name='fin_oferta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vence el'),
        ),
        migrations.AddField(
            model_name='tiendaproducto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial si está en oferta', max_digits=10, null=True),
        ),
    ]
