# Generated by Django 5.2.8 on 2026-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_tiendaproducto_en_oferta_tiendaproducto_fin_oferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Precio especial si está en oferta', max_digits=10, null=True),
        ),
    ]
