# Generated by Django 6.0.2 on 2026-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_tiendaproducto_precio_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tiendaproducto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
