# Generated by Django 6.0.4 on 2026-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'tienda_suscripcion',
            },
        ),
    ]
