# Generated by Django 6.0.4 on 2026-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_tiendasuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendasuscripcion',
            name='fecha_suscripcion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subcripción'),
        ),
    ]
