# Generated by Django 6.0.4 on 2026-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'tienda_banner',
            },
        ),
        migrations.DeleteModel(
            name='HeroBanner',
        ),
    ]
