# Generated by Django 6.0.4 on 2026-10-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_tiendabanner_delete_herobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiendacategoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tienda.tiendacategoria'),
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='meta_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='meta_titulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiendacategoria',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tiendacliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiendaproducto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
