# Generated by Django 6.0.4 on 2026-10-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_tiendabanner_delete_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendacategoria',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tiendaproducto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
