# Generated by Django 6.0.4 on 2026-10-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_alter_tiendacategoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendacategoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
