# Generated by Django 6.0.4 on 2026-10-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_tiendacategoria_options_tiendacategoria_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('tiempo', models.CharField(max_length=50)),
                ('porciones', models.CharField(max_length=50)),
                ('dificultad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('ingrediente_principal', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='recetas/')),
                ('youtube_url', models.URLField(blank=True, help_text='Enlace del video de YouTube de la receta', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
