# Generated by Django 6.0.4 on 2026-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.URLField(help_text='Pega aquí el enlace público de la imagen en Supabase Storage', max_length=500),
        ),
    ]
