# Generated by Django 6.0.4 on 2026-10-10 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_alter_receta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendacupondescuento',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='tiendacupondescuento',
            name='valido_desde',
        ),
        migrations.RemoveField(
            model_name='tiendacupondescuento',
            name='valido_hasta',
        ),
        migrations.AddField(
            model_name='tiendacupondescuento',
            name='creado_en',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tiendacupondescuento',
            name='fecha_expiracion',
            field=models.DateField(blank=True, help_text='Fecha límite de validez (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='tiendacupondescuento',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Porcentaje de descuento (Ej: 10.00 para 10%)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiendacupondescuento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca si el cupón ya no debe usarse'),
        ),
        migrations.AlterField(
            model_name='tiendacupondescuento',
            name='codigo',
            field=models.CharField(help_text='Ej: EXPO2026', max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='tiendacupondescuento',
            table=None,
        ),
    ]
