# Generated by Django 6.0.4 on 2026-10-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_tiendacategoria_slug'),
        ('tienda', '0025_remove_tiendapedido_cliente_and_more'),
    ]

    operations = [
    ]
