# Generated by Django 6.0.4 on 2026-10-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_merge_20261010_1132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendapedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.tiendacliente'),
        ),
        migrations.AddField(
            model_name='tiendapedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiendapedido',
            name='estado_actual',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='tiendacategoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tiendacliente',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tiendacliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tiendacliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, default='2026 02 26'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiendacliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='receta',
            table='tienda_receta',
        ),
        migrations.AlterModelTable(
            name='tiendacupondescuento',
            table='tienda_cupondescuento',
        ),
    ]
